using System.Collections.Generic;

namespace Jw_Quiz_Development
{
    public static class AppText
    {
        private static readonly Dictionary<string, string> Italian = new Dictionary<string, string>
        {
            { "AppTitle", "JW Quiz - Indovina la Storia" },
            { "MainTitle", "JW Quiz" },
            { "Menu", "Menu" },
            { "Stories", "Storie" },
            { "Settings", "Impostazioni" },
            { "Guide", "Guida" },
            { "Help", "Aiuto" },
            { "Exit", "Esci" },
            { "Home", "Pagina iniziale" },
            { "NewEpisodes", "Nuovi Episodi" },
            { "CreateStory", "Crea Nuova Storia" },
            { "UserStories", "Storie Utente" },
            { "NoUserStories", "Nessuna storia utente" },
            { "Language", "Lingua" },
            { "Italian", "Italiano" },
            { "English", "English" },
            { "StoryPrefix", "Storia" },
            { "EpisodePrefix", "Episodio" },
            { "GuessStory", "Indovina la storia!" },
            { "Category", "Categoria" },
            { "ExpectedXp", "XP Previsti" },
            { "ClickImageHint", "Clicca su un'immagine per scoprire un indizio sul racconto" },
            { "RevealImages", "Rivela 2 immagini" },
            { "HideImages", "Nascondi 2 immagini" },
            { "ShowHint", "Mostra indizio" },
            { "HideHint", "Nascondi indizio" },
            { "RevealSolution", "Rivela soluzione" },
            { "HideSolution", "Nascondi soluzione" },
            { "NextStory", "Prossima storia" },
            { "Solution", "Soluzione" },
            { "Note", "Nota" },
            { "StatsTitle", "Statistiche Dettagliate" },
            { "StatsPlayer", "STATISTICHE GIOCATORE" },
            { "StatsLevel", "Livello" },
            { "StatsXp", "Esperienza (XP)" },
            { "StatsProgress", "Progresso" },
            { "StatsPercentage", "Percentuale" },
            { "StatsStartDate", "Data Inizio" },
            { "StatsBadges", "Badge Sbloccati" },
            { "StatsCompletedStories", "STORIE COMPLETATE" },
            { "Times", "volte" },
            { "Fullscreen", "Tutto schermo" },
            { "Windowed", "Minimizza schermo" },
            { "EditorTitle", "Crea Nuova Storia" },
            { "EditorFieldTitle", "Titolo" },
            { "EditorFieldReference", "Riferimento biblico" },
            { "EditorFieldKeyword", "Parola chiave" },
            { "EditorFieldHint", "Indizio testo" },
            { "EditorFieldSolution", "Soluzione" },
            { "EditorFieldEngagement", "Nota engagement" },
            { "EditorFieldInputLanguage", "Lingua di inserimento" },
            { "EditorVisibleImages", "5 immagini visibili" },
            { "EditorHiddenImages", "2 immagini nascoste" },
            { "EditorHintImage", "Immagine indizio" },
            { "Preview", "Anteprima" },
            { "SaveStory", "Salva Storia" },
            { "ChooseImage", "Scegli..." },
            { "ImageGallery", "Scegli un'immagine" },
            { "ImageGalleryHint", "Clicca su un'immagine per selezionarla" },
            { "NoImageAvailable", "Nessuna immagine disponibile." },
            { "IncompleteData", "Dati incompleti" },
            { "SaveCompleted", "Salvataggio completato" },
            { "CreatedStoryDefaultTitle", "Storia Utente" },
            { "DefaultReference", "N/D" },
            { "DefaultKeyword", "Tema" },
            { "DefaultHint", "Indizio non disponibile" },
            { "DefaultSolution", "Soluzione non disponibile" },
            { "DefaultNote", "Nota non disponibile" },
            { "SaveStoryMessage", "Storia salvata con ID {0}." }
        };

        private static readonly Dictionary<string, string> English = new Dictionary<string, string>
        {
            { "AppTitle", "JW Quiz - Guess the Story" },
            { "MainTitle", "JW Quiz" },
            { "Menu", "Menu" },
            { "Stories", "Stories" },
            { "Settings", "Settings" },
            { "Guide", "Guide" },
            { "Help", "Help" },
            { "Exit", "Exit" },
            { "Home", "Home" },
            { "NewEpisodes", "New Episodes" },
            { "CreateStory", "Create New Story" },
            { "UserStories", "User Stories" },
            { "NoUserStories", "No user stories yet" },
            { "Language", "Language" },
            { "Italian", "Italian" },
            { "English", "English" },
            { "StoryPrefix", "Story" },
            { "EpisodePrefix", "Episode" },
            { "GuessStory", "Guess the story!" },
            { "Category", "Category" },
            { "ExpectedXp", "Expected XP" },
            { "ClickImageHint", "Click an image to discover a clue about the story" },
            { "RevealImages", "Reveal 2 images" },
            { "HideImages", "Hide 2 images" },
            { "ShowHint", "Show hint" },
            { "HideHint", "Hide hint" },
            { "RevealSolution", "Reveal solution" },
            { "HideSolution", "Hide solution" },
            { "NextStory", "Next story" },
            { "Solution", "Solution" },
            { "Note", "Note" },
            { "StatsTitle", "Detailed Statistics" },
            { "StatsPlayer", "PLAYER STATISTICS" },
            { "StatsLevel", "Level" },
            { "StatsXp", "Experience (XP)" },
            { "StatsProgress", "Progress" },
            { "StatsPercentage", "Percentage" },
            { "StatsStartDate", "Start Date" },
            { "StatsBadges", "Unlocked Badges" },
            { "StatsCompletedStories", "COMPLETED STORIES" },
            { "Times", "times" },
            { "Fullscreen", "Fullscreen" },
            { "Windowed", "Exit fullscreen" },
            { "EditorTitle", "Create New Story" },
            { "EditorFieldTitle", "Title" },
            { "EditorFieldReference", "Scripture reference" },
            { "EditorFieldKeyword", "Keyword" },
            { "EditorFieldHint", "Hint text" },
            { "EditorFieldSolution", "Solution" },
            { "EditorFieldEngagement", "Engagement note" },
            { "EditorFieldInputLanguage", "Input language" },
            { "EditorVisibleImages", "5 visible images" },
            { "EditorHiddenImages", "2 hidden images" },
            { "EditorHintImage", "Hint image" },
            { "Preview", "Preview" },
            { "SaveStory", "Save Story" },
            { "ChooseImage", "Choose..." },
            { "ImageGallery", "Choose an image" },
            { "ImageGalleryHint", "Click an image to select it" },
            { "NoImageAvailable", "No images available." },
            { "IncompleteData", "Incomplete data" },
            { "SaveCompleted", "Save completed" },
            { "CreatedStoryDefaultTitle", "User Story" },
            { "DefaultReference", "N/A" },
            { "DefaultKeyword", "Theme" },
            { "DefaultHint", "Hint not available" },
            { "DefaultSolution", "Solution not available" },
            { "DefaultNote", "Note not available" },
            { "SaveStoryMessage", "Story saved with ID {0}." }
        };

        public static string Get(string key)
        {
            return Get(LanguageManager.CurrentLanguage, key);
        }

        public static string Get(AppLanguage language, string key)
        {
            string value;
            var table = language == AppLanguage.English ? English : Italian;
            return table.TryGetValue(key, out value) ? value : key;
        }
    }
}